--- mermaid code


---
config:
  look: classic
  theme: neo
  layout: fixed
---
flowchart RL
 subgraph INVOKE["LLM Invocation Layer"]
        MG["Contextual Authorization Layer (PIM only)"]
        LLM["LLM Client"]
  end
 subgraph DATA["Data Layer"]
        LOG["Experiment Logger"]
        DBS["Database Service"]
  end
 subgraph DB["Microsoft SQL Server"]
        UDATA["Users<br>user_preferences"]
        CDATA["Conversations<br>chat_messages"]
        ELOGS["experiment_logs"]
        RMEM["Reserved Memory Tables<br>user_behavior_profile<br>conversation_context<br>academic_memory"]
  end
    UI["React + Vite"] --> API["API & Auth Layer"]
    API --> Router["Domain Router"] & UI
    Router --> USP["Personal Interaction Module (PIM)"] & ACAD["Academic Handler"]
    USP --> MG & PLI["Persistence & Logging Interface"]
    MG --> LLM & PLI
    ACAD --> LLM & PLI
    LLM --> EXT["LLM Provider API"] & API
    EXT --> LLM
    LOG --> PLI
    PLI --> DBS
    DBS --> DB
    LOG -.-> ELOGS
    n1["Figure 2. High-Level Architecture of AURA v1.0"]

    n1@{ shape: text}
     MG:::memory
     LLM:::llm
     LOG:::logger
     DBS:::data
     UI:::frontend
     API:::backend
     Router:::backend
     USP:::domain
     ACAD:::domain
     PLI:::data
     EXT:::external
    classDef frontend fill:#fdf6ec,stroke:#333,stroke-width:1px
    classDef backend fill:#eef3fb,stroke:#333,stroke-width:1px
    classDef domain fill:#e8f6ef,stroke:#333,stroke-width:1px
    classDef memory fill:#f5e8ff,stroke:#333,stroke-width:1px
    classDef llm fill:#f5e8ff,stroke:#333,stroke-width:1px
    classDef external fill:#ffffff,stroke:#333,stroke-width:1px
    classDef data fill:#fff4e6,stroke:#333,stroke-width:1px
    classDef logger fill:#fff4e6,stroke:#333,stroke-width:1px